from .analysis_insights import install_analysis_insights
from .beta_access import install_beta_access
from .bot import LeadPilotBot, run
from .database import Database
from .global_price_mode import install_global_price_mode
from .hide_settings_button import install_hide_settings_button
from .personal_lead_ids import install_personal_lead_ids
from .project_button_guard import install_project_button_guard
from .project_questionnaires import install_project_questionnaires
from .project_radars import install_project_radars
from .project_schema_hotfix import install_project_schema_hotfix
from .project_search_context import install_project_search_context
from .radar_inline_controls import install_radar_inline_controls
from .radar_menu_access_fix import install_radar_menu_access_fix
from .role_policy import install_role_policy
from .scheduled_radars import install_scheduled_radars
from .search_quality import install_search_quality
from .serpapi import SerpApiClient
from .trial_limits_guard import install_trial_limits_guard
from .usage_limits import install_usage_limits
from .user_commands import install_user_commands


install_beta_access(LeadPilotBot, Database)
install_personal_lead_ids(Database)
install_project_questionnaires(LeadPilotBot, Database)
install_project_radars(LeadPilotBot, Database)
install_analysis_insights(LeadPilotBot, Database)
install_usage_limits(LeadPilotBot, Database)
install_project_schema_hotfix(Database)
install_search_quality(LeadPilotBot, SerpApiClient)
install_project_search_context(LeadPilotBot, SerpApiClient)
install_role_policy(LeadPilotBot)
install_global_price_mode(LeadPilotBot)
install_project_button_guard(LeadPilotBot)
install_scheduled_radars(LeadPilotBot, Database)
install_radar_menu_access_fix(LeadPilotBot)
install_user_commands(LeadPilotBot)
install_radar_inline_controls(LeadPilotBot)
install_trial_limits_guard(LeadPilotBot)
install_hide_settings_button(LeadPilotBot)


if __name__ == "__main__":
    run()
